[tool.poetry]
authors = ["SaitoTsutomu <tsutomu7@hotmail.co.jp>"]
classifiers = [
  "Development Status :: 1 - Planning",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
  "Topic :: Software Development",
]
description = "`ortoolpy` is a package for Operations Research."
homepage = "https://github.com/SaitoTsutomu/ortoolpy"
license = "Apache-2.0"
name = "ortoolpy"
readme = "README.rst"
version = "0.6.3"

[tool.poetry.dependencies]
more-itertools = "^10.1"
# change to ^2.0 at later
pandas = ">=1.5.3"
pulp = "^2.7"
python = "^3.11"

[tool.poetry.group.dev.dependencies]
black = "^23.7"
flake8 = "^6.1"
isort = "^5.12"
jupyterlab = "^4.0"
matplotlib = "^3.7"
mypy = "^1.5"
networkx = "^3.1"
pytest = "^7.4"
snapshottest = "^0.6"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
