[tool.poetry]
authors = ["SaitoTsutomu <tsutomu7@hotmail.co.jp>"]
classifiers = [
  "Development Status :: 1 - Planning",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
  "Topic :: Software Development",
]
description = "`ortoolpy` is a package for Operations Research."
homepage = "https://github.com/SaitoTsutomu/ortoolpy"
license = "Apache-2.0"
name = "ortoolpy"
readme = "README.rst"
version = "0.7.1"

[tool.poetry.dependencies]
more-itertools = "^10.3"
pandas = "^2.2"
pulp = "^2.8"
python = "^3.12"

[tool.poetry.group.dev.dependencies]
jupyterlab = "^4.2"
matplotlib = "^3.9"
networkx = "^3.3"
pytest = "^8.2"
pytest-snapshot = "^0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
