[tool.poetry]
authors = ["SaitoTsutomu <tsutomu7@hotmail.co.jp>"]
classifiers = [
  "Development Status :: 1 - Planning",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
  "Topic :: Software Development",
]
description = "`ortoolpy` is a package for Operations Research."
homepage = "https://github.com/SaitoTsutomu/ortoolpy"
license = "Apache-2.0"
name = "ortoolpy"
readme = "README.rst"
version = "0.5.0"

[tool.poetry.dependencies]
more-itertools = "^9.0"
pandas = "^1.5"
pulp = "^2.7"
python = "^3.11"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
flake8 = "^6.0.0"
isort = "^5.12.0"
jupyterlab = "^3.6.1"
matplotlib = "^3.7.0"
mypy = "^1.0.1"
networkx = "^3.0"
pytest = "^7.2.1"
snapshottest = "^0.6.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
