[tool.poetry]
authors = ["SaitoTsutomu <tsutomu7@hotmail.co.jp>"]
classifiers = [
  "Development Status :: 1 - Planning",
  "License :: OSI Approved :: Python Software Foundation License",
  "Programming Language :: Python",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
  "Topic :: Software Development",
]
description = "`ortoolpy` is a package for Operations Research."
homepage = "https://github.com/SaitoTsutomu/ortoolpy"
license = "PSFL"
name = "ortoolpy"
readme = "README.rst"
version = "0.2.37"

[tool.poetry.dependencies]
more-itertools = "^8.6.0"
pandas = "^1.1.4"
pulp = "^2.3.1"
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
isort = "^5.6.4"
jupyter = "^1.0.0"
mypy = "^0.790"
pytest = "^6.1.2"

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
