[tool.poetry]
authors = ["SaitoTsutomu <tsutomu7@hotmail.co.jp>"]
classifiers = [
  "Development Status :: 1 - Planning",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
  "Topic :: Software Development",
]
description = "`ortoolpy` is a package for Operations Research."
homepage = "https://github.com/SaitoTsutomu/ortoolpy"
license = "Apache-2.0"
name = "ortoolpy"
readme = "README.rst"
version = "0.4.0"

[tool.poetry.dependencies]
more-itertools = "^8.13.0"
pandas = "^1.4.3"
pulp = "^2.6.0"
python = "^3.10"

[tool.poetry.dev-dependencies]
black = "^22.6"
flake8 = "^4.0.1"
isort = "^5.10.1"
jupyterlab = "^3.4.3"
matplotlib = "^3.5.2"
mypy = "^0.961"
networkx = "^2.8.4"
pytest = "^7.1.2"
snapshottest = "^0.6.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
